services:
  publicapi:
    image: public-api:latest
    build:
      context: .
      dockerfile: src/Api/PublicApi/Dockerfile
    env_file:
       - ./src/Api/PublicApi/.env
    
    ports:
      - "8080:8080"
      - "7256:7256"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: "https://+:7256;http://+:8080"
      ASPNETCORE_Kestrel__Certificates__Default__Path: /https/localhost.pfx
      ASPNETCORE_Kestrel__Certificates__Default__Password: "devpassword"
    volumes:
      - ./src/Api/PublicApi/certificates:/https/:ro
      - ./src/Api/PublicApi/.env:/app/.env:ro

  veterinary.database:
    image: postgres:17 
    environment:
    - POSTGRES_DB=test_db
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=2501
    volumes:
      - veterinary-db-data:/var/lib/postgresql
    restart: unless-stopped
    ports:
      - "5432:5432"
 
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: billelmh501@gmail.com
      PGADMIN_DEFAULT_PASSWORD: billel501
    ports:
      - "5050:80"
    depends_on:
      - veterinary.database

volumes:
  veterinary-db-data:
