// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Modules.Attendence.Infrastructure.Presistance;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Modules.Attendence.Migrations
{
    [DbContext(typeof(AttendanceDbContext))]
    [Migration("20260903132538_SnakeCaseColumns")]
    partial class SnakeCaseColumns
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("attendance")
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Modules.Attendence.Domain.AttendenceRecords.AttendanceRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CheckInAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("check_in_at");

                    b.Property<DateTime?>("CheckOutAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("check_out_at");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<TimeSpan>("EarlyLeaveTime")
                        .HasColumnType("interval")
                        .HasColumnName("early_leave_time");

                    b.Property<string>("EmployeeId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("employee_id");

                    b.Property<bool>("IsAbsent")
                        .HasColumnType("boolean")
                        .HasColumnName("is_absent");

                    b.Property<TimeSpan>("LateTime")
                        .HasColumnType("interval")
                        .HasColumnName("late_time");

                    b.Property<Guid>("MachineId")
                        .HasColumnType("uuid")
                        .HasColumnName("machine_id");

                    b.Property<TimeSpan>("Overtime")
                        .HasColumnType("interval")
                        .HasColumnName("overtime");

                    b.Property<TimeSpan>("WorkedTime")
                        .HasColumnType("interval")
                        .HasColumnName("worked_time");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId", "CheckInAt");

                    b.ToTable("attendance_records", "attendance");
                });

            modelBuilder.Entity("Modules.Attendence.Domain.Machines.AttendenceMachine", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ip_address");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<int>("MachineNumber")
                        .HasColumnType("integer")
                        .HasColumnName("machine_number");

                    b.Property<int>("Port")
                        .HasColumnType("integer")
                        .HasColumnName("port");

                    b.Property<int>("Type")
                        .HasMaxLength(50)
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.ToTable("machines", "attendance");
                });

            modelBuilder.Entity("Modules.Attendence.Domain.PunchPolling.PunchPollingSettings", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("IntervalMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("interval_minutes");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("is_enabled");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.ToTable("punch_polling_settings", "attendance");
                });

            modelBuilder.Entity("Modules.Attendence.Domain.Punches.Punch", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_on_utc");

                    b.Property<int>("EmployeeBadge")
                        .HasColumnType("integer")
                        .HasColumnName("employee_badge");

                    b.Property<Guid>("MachineId")
                        .HasColumnType("uuid")
                        .HasColumnName("machine_id");

                    b.Property<DateTime>("PunchOccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("punch_occurred_at");

                    b.HasKey("Id");

                    b.HasIndex("MachineId", "EmployeeBadge", "PunchOccurredAt");

                    b.ToTable("punches", "attendance");
                });

            modelBuilder.Entity("Modules.Shared.Infrastructure.Outbox.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("content");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_on_utc");

                    b.Property<DateTime?>("LastAttemptOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_attempt_on_utc");

                    b.Property<string>("LastError")
                        .HasColumnType("text")
                        .HasColumnName("last_error");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.Property<DateTime?>("ProcessedOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_on_utc");

                    b.Property<int>("RetryCount")
                        .HasColumnType("integer")
                        .HasColumnName("retry_count");

                    b.HasKey("Id");

                    b.HasIndex("ProcessedOnUtc")
                        .HasDatabaseName("IX_outbox_messages_processed_on_utc")
                        .HasFilter("\"processed_on_utc\" IS NULL");

                    b.ToTable("outbox_messages", "shared", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
