// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Modules.Employees.Infrastructure.Presistance;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Modules.Employees.Migrations
{
    [DbContext(typeof(EmployeeDbContext))]
    [Migration("20260828131118_FixCascadeDeleteForWorkSchedules")]
    partial class FixCascadeDeleteForWorkSchedules
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("employees")
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Modules.Employees.Domain.EmployeeGroups.EmployeeGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_on_utc");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<bool>("IsSecurity")
                        .HasColumnType("boolean")
                        .HasColumnName("is_security");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<DateOnly>("RotationStartDate")
                        .HasColumnType("date")
                        .HasColumnName("rotation_start_date");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_employee_groups_name");

                    b.ToTable("employee_groups", "employees");
                });

            modelBuilder.Entity("Modules.Employees.Domain.EmployeeGroups.Rotation.RotationEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_on_utc");

                    b.Property<DateTime?>("DeletedOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("EmployeeGroupId")
                        .HasColumnType("uuid")
                        .HasColumnName("employee_group_id");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<int>("Position")
                        .HasColumnType("integer")
                        .HasColumnName("position");

                    b.Property<Guid?>("WorkScheduleId")
                        .HasColumnType("uuid")
                        .HasColumnName("work_schedule_id");

                    b.HasKey("Id");

                    b.HasIndex("WorkScheduleId");

                    b.HasIndex("EmployeeGroupId", "Position")
                        .IsUnique()
                        .HasDatabaseName("ix_rotation_entries_employee_group_id_position");

                    b.ToTable("rotation_entries", "employees");
                });

            modelBuilder.Entity("Modules.Employees.Domain.EmployeeGroups.WorkSchedules.WorkSchedule", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AllowedCheckInLatenessMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("allowed_check_in_lateness_minutes");

                    b.Property<int>("AllowedCheckOutEarlinessMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("allowed_check_out_earliness_minutes");

                    b.Property<TimeOnly>("BreakEndTime")
                        .HasColumnType("time without time zone")
                        .HasColumnName("break_end_time");

                    b.Property<TimeOnly>("BreakStartTime")
                        .HasColumnType("time without time zone")
                        .HasColumnName("break_start_time");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_on_utc");

                    b.Property<Guid>("EmployeeGroupId")
                        .HasColumnType("uuid")
                        .HasColumnName("employee_group_id");

                    b.Property<int>("EndDayOffset")
                        .HasColumnType("integer")
                        .HasColumnName("end_day_offset");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<TimeOnly>("ShiftEndTime")
                        .HasColumnType("time without time zone")
                        .HasColumnName("shift_end_time");

                    b.Property<TimeOnly>("ShiftStartTime")
                        .HasColumnType("time without time zone")
                        .HasColumnName("shift_start_time");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeGroupId");

                    b.ToTable("work_schedules", "employees");
                });

            modelBuilder.Entity("Modules.Shared.Infrastructure.Outbox.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("content");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_on_utc");

                    b.Property<DateTime?>("LastAttemptOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_attempt_on_utc");

                    b.Property<string>("LastError")
                        .HasColumnType("text")
                        .HasColumnName("last_error");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.Property<DateTime?>("ProcessedOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_on_utc");

                    b.Property<int>("RetryCount")
                        .HasColumnType("integer")
                        .HasColumnName("retry_count");

                    b.HasKey("Id");

                    b.HasIndex("ProcessedOnUtc")
                        .HasDatabaseName("IX_outbox_messages_processed_on_utc")
                        .HasFilter("\"processed_on_utc\" IS NULL");

                    b.ToTable("outbox_messages", "shared", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("Modules.Employees.Domain.EmployeeGroups.Rotation.RotationEntry", b =>
                {
                    b.HasOne("Modules.Employees.Domain.EmployeeGroups.EmployeeGroup", "EmployeeGroup")
                        .WithMany("RotationEntries")
                        .HasForeignKey("EmployeeGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_rotation_entries_employee_groups_employee_group_id");

                    b.HasOne("Modules.Employees.Domain.EmployeeGroups.WorkSchedules.WorkSchedule", "WorkSchedule")
                        .WithMany()
                        .HasForeignKey("WorkScheduleId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_rotation_entries_work_schedules_work_schedule_id");

                    b.Navigation("EmployeeGroup");

                    b.Navigation("WorkSchedule");
                });

            modelBuilder.Entity("Modules.Employees.Domain.EmployeeGroups.WorkSchedules.WorkSchedule", b =>
                {
                    b.HasOne("Modules.Employees.Domain.EmployeeGroups.EmployeeGroup", "EmployeeGroup")
                        .WithMany("WorkSchedules")
                        .HasForeignKey("EmployeeGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_work_schedules_employee_groups_employee_group_id");

                    b.Navigation("EmployeeGroup");
                });

            modelBuilder.Entity("Modules.Employees.Domain.EmployeeGroups.EmployeeGroup", b =>
                {
                    b.Navigation("RotationEntries");

                    b.Navigation("WorkSchedules");
                });
#pragma warning restore 612, 618
        }
    }
}
